### ISSUE TITLE
Question about approaching Flic hub and its IR beamer

### ISSUE THREAD

**Issue by dimitrieh** [Mincka/flic-reverse#1]
hi @Mincka,

Feel free to delete this issue if it is not correct to post it here. I was wondering if you could give me your insights on the following question regarding the flic hub. This as you seem to have in-depth knowledge on its inner workings.

The flic hub comes with a IR blaster/beamer which acts as an entity that can be triggered. To let it be triggered by a flic button is easy, but I would love an external tool (zapier/ifttt/google asssitent/etc) trigger it instead based on some conditions I configure.

Would you know if this is doable with the flic SDK?

Kind regards,

**Comment by Mincka** [comment]
Hi,
At the time I did my research, the SDK was not yet publicly available.

From what I see, you may be able to listen for events on TCP/UDP using the SDK.
https://hubsdk.flic.io/static/documentation/#50_new_net_server
https://github.com/loosrob/Flic-Hub-SDK-scripts/blob/main/udp_message.js

However, I did not find a specific example for listening to events and react.

Another solution, less sexy, would be to implement polling using the HTTP class.
In this case, from the Hub, you query the status of a switch, binary sensor or a sensor in Home Assistant every second.

Based on the response (state), you trigger your IR command.
Imagine your sensor is something like "IR Command" that will be the "Uint32Array" of the IR code to send.
When you need to trigger a command through the IR blaster, you set its state to the IR command code.

Then, using the callback response you play the message through the IR blaster:
https://hubsdk.flic.io/static/documentation/#37_play
